# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          BIND-ADDRESS: 0.0.0.0
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: dump
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root  -e ../db/dump/garbage_0304.sql
      # - name: tidy
      #   run: go mod tidy
      - name: init
        run: |
          go get -v -t -d ./...
      - name: test
        run: |
          go test -v  ./...
